### ISSUE TITLE
Rebuild Home Page

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#386]
_Comment if you are interested in working on this issue!_

## Requirements

_Requirements are open to discussion._

The Home Page has several sub-components. The purpose of this issue is to rebuild the top level structure including elements for:
- Create `HomePage` component.
- Migrate [homepage-refresh](https://github.com/sparkbox/sparkeats/blob/main/legacy/views/pages/homepage-refresh.ejs) to `HomePage`.
- Create placeholder elements for #402 and #404.

## References

- https://eats.seesparkbox.com/refresh

<img width="896" alt="Screen Shot 2022-10-09 at 5 36 46 PM" src="https://user-images.githubusercontent.com/16216104/194746756-198ec53e-84f6-4573-9e8b-b12b2494b66d.png">

**Comment by arnest00** [comment]
@yosevu Is the goal to rebuild the hompage such that the root route will feature the design found on `/refresh`?

**Comment by yosevu** [comment]
> @yosevu Is the goal to rebuild the homepage such that the root route will feature the design found on `/refresh`?

Yes, that's the goal. So this actually depends on #398 to Add React Router and Routes. I will add some details to the issue.
