### ISSUE TITLE
Add and Configure Cypress

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#387]
## Requirements

_Requirements are open to discussion._

- Install Cypress
- Configure Cypress for E2E testing in Chrome
- Update tsconfig.json for Cypress
- Add a test script to run tests from the command line
---

## Home Page (Locations) Specification (Optional)

This may be completed in a separate issue depending on your experience writing Cypress tests.

-  Create a spec for the Home Page pointing to https://eats.seesparkbox.com/refresh until the Locations Page is rebuilt. See the Locations Page specifications in #407 for details.

## Out of Scope

- Writing tests for other pages
- Adding an e2e test job to .github/workflows/web.yml

## References

- https://docs.cypress.io/guides/getting-started/installing-cypress
- https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfig-json
- https://eats.seesparkbox.com/refresh
- https://www.figma.com/file/YEaOqHcQNa79LFpINHBL57/Sparkeats?node-id=0%3A1

**Comment by shyambh** [comment]
Hi @yosevu , I can add some Cypress tests to the app.

**Comment by yosevu** [comment]
Hello @shyambh, thanks for reaching out! Let me add some details to the issue and you can let me know what you think and what you are interested in working on.

**Comment by yosevu** [comment]
I added requirements to the issue @shyambh. Let me know if you have any questions or ideas.

**Comment by shyambh** [comment]
Hi @yosevu . I tried to run the app locally, and when I run the app, it opens up a blank page which says 'hello sparkeats'.
Can you please mention if I need to do anything else to run the app?

Also, do you just want me to add Cypress configuration because right now there isn't much functionality to test (beside the 'hello sparkeats' text).

Below is the screenshot of the local instance of the app:

![image](https://user-images.githubusercontent.com/27716952/194766256-b80e2c3c-65e8-4758-a81b-fb696266cee3.png)

**Comment by yosevu** [comment]
> Hi @yosevu . I tried to run the app locally, and when I run the app, it opens up a blank page which says 'hello sparkeats'. Can you please mention if I need to do anything else to run the app?
> 
> Also, do you just want me to add Cypress configuration because right now there isn't much functionality to test (beside the 'hello sparkeats' text).
> 
> Below is the screenshot of the local instance of the app:
> 
> ![image](https://user-images.githubusercontent.com/27716952/194766256-b80e2c3c-65e8-4758-a81b-fb696266cee3.png)

@shyambh, we are just getting started rebuilding the app. We are building the Locations Page (Home) first, but it isn't done yet. You can still write tests, however, pointing to https://eats.seesparkbox.com/refresh for now. I also updated the issue with more details. Let me know if that makes sense or not and if you have other questions.

**Comment by shyambh** [comment]
> > Hi @yosevu . I tried to run the app locally, and when I run the app, it opens up a blank page which says 'hello sparkeats'. Can you please mention if I need to do anything else to run the app?
> > Also, do you just want me to add Cypress configuration because right now there isn't much functionality to test (beside the 'hello sparkeats' text).
> > Below is the screenshot of the local instance of the app:
> > ![image](https://user-images.githubusercontent.com/27716952/194766256-b80e2c3c-65e8-4758-a81b-fb696266cee3.png)
> 
> @shyambh, we are just getting started rebuilding the app. We are building the Locations Page (Home) first, but it isn't done yet. You can still write tests, however, pointing to https://eats.seesparkbox.com/refresh for now.
> 
> Please review the "Requirements" section in this issue for to understand the scope of this issue. I also updated it with more details. Let me know if that makes sense or not and if you have other questions.

Thank you. I will get started. For now, I will set up Cypress and write a few tests as per the requirements.
