### ISSUE TITLE
Add and Configure Prettier

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#388]
## Requirements

_Requirements are open for discussion._

- Add Prettier
- Configure Prettier
- Add `format` script to package.json to format the `src` directory.

## References
- https://prettier.io/docs/en/install.html

**Comment by Dun-sin** [comment]
hi, can i try this?

**Comment by yosevu** [comment]
Hello @Dun-sin, you sure can. I will add some details to this issue and assign it to you if you give me a thumbs up 👍. Have you tried to set up the project for development?

**Comment by Dun-sin** [comment]
Not yet was waiting to be assigned

**Comment by yosevu** [comment]
I created three separate issues from this:

- Add and Configure Prettier (This one)
- Add and Configure TypeScript ESLint #392 
- Add and Configure Stylelint #394 

Which one would you like me to assign to you @Dun-sin?
-

**Comment by yosevu** [comment]
> > I created three separate issues from this:
> > 
> > * Add and Configure Prettier (This one)
> > * Add and Configure TypeScript ESLint [Add and Configure TypeScript ESLint #392](https://github.com/sparkbox/sparkeats/issues/392)
> > * Add and Configure Stylelint [Add and Configure Stylelint #394](https://github.com/sparkbox/sparkeats/issues/394)
> > 
> > Which one would you like me to assign to you @Dun-sin?
> 
> Why so many lints?

I know it does seem like a lot, but these are lining tools for TypeScript, SCSS, and code formatting.

- ESLint is for linting React and TypeScript
- Stylelint is for lining styles
- Prettier is for consistent formatting

I created separate issues for handling each of them separately so that it is more manageable.

**Comment by Dun-sin** [comment]
> > > I created three separate issues from this:
> > > 
> > > * Add and Configure Prettier (This one)
> > > * Add and Configure TypeScript ESLint [Add and Configure TypeScript ESLint #392](https://github.com/sparkbox/sparkeats/issues/392)
> > > * Add and Configure Stylelint [Add and Configure Stylelint #394](https://github.com/sparkbox/sparkeats/issues/394)
> > > 
> > > Which one would you like me to assign to you @Dun-sin?
> > 
> > Why so many lints?
> 
> I know it does seem like a lot, but these are lining tools for TypeScript, SCSS, and code formatting.
> 
> - ESLint is for linting React and TypeScript
> - Stylelint is for lining styles
> - Prettier is for consistent formatting
> 
> I created separate issues for handling each of them separately so that it is more manageable.
> 

Yeah alright that makes sense
