### ISSUE TITLE
Add Continuous Deployment Workflow

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#391]
## Requirements 

_Requirements are open for discussion._

- Start with a simple deployment process such as with GitHub Pages
- Create a deploy workflow that is triggered on `push` to `main`

## References

- https://vitejs.dev/guide/static-deploy.html#github-pages

**Comment by KehindeBello** [comment]
I'll like to work on this issue. Can you assign it to me?
Also, what's your tool preference?
