### ISSUE TITLE
Add and Configure TypeScript ESLint

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#392]
## Requirements

- Add TypeScript ESLint dependencies
- Add eslint-config-prettier
- Use eslint and typescript-eslint recommended, and prettier configuration
- Add `lint` script to package.json

## References
- https://typescript-eslint.io/docs/
- https://github.com/prettier/eslint-config-prettier

**Comment by JoelLau** [comment]
hi @yosevu , can i take this up?

**Comment by yosevu** [comment]
Hello @JoelLau, go for it!

**Comment by JoelLau** [comment]
sorry, missed the notification. will send a PR soon 👍

**Comment by JoelLau** [comment]
^ lmk if i understood the requirements correctly or missed anything :)
