### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#396]
## Requirements

_Requirements are open to discussion._

- Keep it simple

## References

- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by neutr0n420** [comment]
I would like to work on this issue? should I make a new templete.md file and add the the template in that file?

**Comment by yosevu** [comment]
Hello @neutr0n420, go for it. I'll assign it to you.

**Comment by neutr0n420** [comment]
Hey 

> Hello @neutr0n420, go for it! I'll assign it to you.

Hey I had made a pr can you have a look at it #397
