### ISSUE TITLE
Rebuild Site Header

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#401]
_Comment if you are interested in working on this issue!_

## Requirements

_Requirements are open to discussion._

- Create a `Site Header` component.
- Migrate [sparkeats-header](https://github.com/sparkbox/sparkeats/blob/main/legacy/views/partials/sparkeats-header.ejs) to `Site Header`.
- Wrap [the home link](https://github.com/sparkbox/sparkeats/blob/main/legacy/views/partials/sparkeats-header.ejs#L3) in a nav

## References

- https://eats.seesparkbox.com/refresh
- #407 
- #413

<img width="895" alt="Screen Shot 2022-10-09 at 5 35 46 PM" src="https://user-images.githubusercontent.com/16216104/194746629-72a86a39-5988-4989-8d2d-da9fe393e2b1.png">

**Comment by catheraaine** [comment]
Meee I want to do this one!

**Comment by yosevu** [comment]
Sounds good @catheraaine! I just add the routes so there's a place for the Sparkeats Header now.
