### ISSUE TITLE
Rebuild Home Header

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#402]
## Requirements

_Requirements are open to discussion and revision._

The Home Page Header has two subcomponents: Locations Menu and Sparkeats Subtitle.

- Create a `HomeHeader` component
- Migrate [homepage-header.ejs](https://github.com/sparkbox/sparkeats/blob/main/legacy/views/partials/homepage-header.ejs) to this component
- Create a placeholder component for the `LocationMenu`. This component will be rebuilt in #432. 
- Create a component for the Home Subtitle.
- Migrate [sparkeats-subtitle.ejs](https://github.com/sparkbox/sparkeats/blob/main/legacy/views/partials/sparkeats-subtitle.ejs) to this component.

## References

- https://eats.seesparkbox.com/refresh
- #413 

Current:
<img width="896" alt="Screen Shot 2022-10-09 at 5 37 54 PM" src="https://user-images.githubusercontent.com/16216104/194746719-4409e1e7-cae0-4746-8bd7-64d1ee16cc4d.png">

Updated:
<img width="896" alt="Screen Shot 2022-10-26 at 9 13 06 AM" src="https://user-images.githubusercontent.com/16216104/197904993-0c60c6f0-c8a8-4b63-9924-fee5a30e5767.png">

**Comment by arnest00** [comment]
I'll work on this!

**Comment by yosevu** [comment]
I was looking at this again and decided to update the requirements to separate #432 @arnest00. No worries if you are already working on it and want to include it though, your PR can cover both issues.
