### ISSUE TITLE
Rebuild Home Page Location Cards

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#404]
_Comment if you are interested in working on this issue!_

## Requirements

_Requirements are open to discussion._

- Create a `Location Cards` component.
- Migrate [place-card-container.ejs](https://github.com/sparkbox/sparkeats/blob/main/legacy/views/partials/place-card-container.ejs) to `Location Cards`.
- Render a list of placeholder elements until `LocationCard` #406 is complete. 

## References

- https://eats.seesparkbox.com/refresh
- #407 
- #413

<img width="895" alt="Screen Shot 2022-10-09 at 5 37 11 PM" src="https://user-images.githubusercontent.com/16216104/194746684-464b2e58-4e39-4bf0-8324-98b7b9fab6df.png">

**Comment by g1mishra** [comment]
Hii @yosevu 

Assign it to me, I'll work on this.

**Comment by shivam1317** [comment]
Hey can you assign me this issue?

**Comment by yosevu** [comment]
Hello @shivam1317, assigned to you. This issue is a subcomponent of #386, so we won't be able to integrate it until that is done. You may go ahead rebuild it, however, and import it into App.tsx for now and we will move it later. Does that make sense?

As as side note, I may add Storybook, so components like this can be built independently in a separate environment in situations like this.
