### ISSUE TITLE
Rebuild Location Page

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#414]
## Requirements

_Requirements are open to discussion._

The Location Page has several subcomponents. The purpose of this issue is to rebuild the top level structure using placeholder elements for the sub-components listed below.

- Create a `LocationPage` component.
- Integrate the component in [main.tsx](https://github.com/sparkbox/sparkeats/blob/main/src/main.tsx#L12) and render it at the `/locations/:id` route.
- Migrate [review-page.ejs](https://github.com/sparkbox/sparkeats/blob/main/legacy/views/partials/review-page.ejs).
- Create placeholder elements for subcomponents

### Subcomponents

- `LocationNavigation`
- `LocationHeader`
- `LocationReviews`
- `LocationOverview`

## References

- https://eats.seesparkbox.com/refresh/2
- #407
- #413 

<img width="896" alt="Screen Shot 2022-10-15 at 3 55 31 PM" src="https://user-images.githubusercontent.com/16216104/195973890-42113844-7af3-418c-993a-23b9db31d880.png">

**Comment by mnosov622** [comment]
Hi @yosevu !

I'm willing to work on that. Could you please provide more details about what should be changed ?

Thank you.

**Comment by yosevu** [comment]
Hi @mnosov622, I added details for this issue and assigned it to you. Let me know if you have questions!

**Comment by mnosov622** [comment]
Hi !

Thank you. I will work on that.

**Comment by mnosov622** [comment]
So we can omit the reviews itself ? What should happen when we click on "1 Review" ?

**Comment by yosevu** [comment]
> @yosevu So we can omit the reviews itself ? What should happen when we click on "1 Review" ?

Yes, this is a very simple issue just to set up the structure for the Location Page. It should only include code in `review-page.ejs` and use placeholder elements like `<div>Location Overview</div>` for the subcomponents. "1 Review" is a part of the #420, so will be implemented there. Does that make sense?

**Comment by mnosov622** [comment]
Yes, got it.

Thank you!

**Comment by yosevu** [comment]
Make sure to update your branch with `main` @mnosov622. I merged Rebuild Home Page #421, which you can also use as a reference for the Location Page.
