### ISSUE TITLE
Rebuild New Location Page

### ISSUE THREAD

**Issue by yosevu** [sparkbox/sparkeats#415]
_Comment if you are interested in working on this issue!_

## Requirements

_Requirements are open to discussion and revision._

- Create a `NewLocationPage` component.
- Migrate [places/new.ejs](https://github.com/sparkbox/sparkeats/blob/main/legacy/views/pages/places/new.ejs)
- Create a placeholder for the Image upload form field and related code such as [showFile.js](https://github.com/sparkbox/sparkeats/blob/main/legacy/assets/js/local/showFile.js). This will be completed in a separate issue.
  - Replace instances of "place" with "location"
  - Create subcomponents as necessary.
- Update the form fields to match the updated [Location type](https://github.com/sparkbox/sparkeats/blob/main/src/types/sparkeats.ts#L1).
- Navigate to `/locations/:id` passing the location data as state on the form submit event.
- Add Cypress tests based on #407

## References

- https://sparkbox.github.io/sparkeats/locations/new
- https://eats.seesparkbox.com/refresh/2
- #407
- #413 

<img width="896" alt="Screen Shot 2022-10-26 at 10 03 02 AM" src="https://user-images.githubusercontent.com/16216104/197910427-2ed83ecc-6b72-487f-b502-b8a53340867e.png">

**Comment by theogainey** [comment]
@yosevu I want to do this one

**Comment by yosevu** [comment]
> @yosevu I want to do this one

Hi @theogainey! Sounds good. I added some details to the issue. Let me know if you have questions or suggestions.

**Comment by yosevu** [comment]
Completed with #433.
